import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from '@react-oauth/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <GoogleOAuthProvider clientId="463494154021-qut3c7411u9ql43onvvs28dokuk7k3i8.apps.googleusercontent.com">
        {children}
        
        <Toaster  />
        {children}
        </GoogleOAuthProvider>;
      </body>
    </html>
  );
}
